"""The guard's restore must not run on a false premise, and must not lie.

Two defects in the recovery branch of `Verify the build is reproducible`,
both proven against a real bare remote before being fixed here.

F5  The restore was UNCONDITIONAL, but its comment states the premise it
    depends on: "The index still holds the first build". That is only true if
    the `git add -A site/` above SUCCEEDED. When `git add` is what failed, the
    index still holds HEAD, so `git checkout -- site/` reverts the worktree to
    the PREVIOUS cycle's build — and `git clean -fdq site/` then deletes any
    page the first build added, because a failed `git add` left it untracked.
    The cycle's data/ commits regardless, so the remote receives last cycle's
    HTML beside this cycle's prices. Measured on a lab remote:
    site/index.html and site/plants/rose.html arrived at the previous cycle's
    content while data/prices/rose.jsonl carried the new price.

F6  `git checkout`'s exit code was discarded. A crashing rebuild plus a
    failing `git checkout` published half-written HTML and a clobbered
    site/bot.html — a hand-maintained file the build does not own — while the
    ::error:: annotation asserted "The first build was restored and still
    publishes". An annotation that reports the opposite of what happened is
    worse than no annotation: it sends the reader to look somewhere else.

The fix for F5 is to gate the restore on `add_rc`; doing nothing is strictly
better, because the first build is still sitting in the worktree. The fix for
F6 is to capture the rc and report it. Neither fix can make a failed checkout
succeed — what it can do is stop the annotation from claiming it did.

Everything here runs the step body VERBATIM out of the YAML under the shell
GitHub Actions uses, in a real throwaway git repository. Nothing asserts a
property in prose.
"""

import os
import shutil
import stat
import subprocess
import textwrap

import pytest
import yaml

WORKFLOW = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    ".github", "workflows", "scrape.yml",
)
GUARD_STEP = "Verify the build is reproducible"
COMMIT_STEP = "Commit updated price data"

BASH = shutil.which("bash")
GIT = shutil.which("git")
needs_bash = pytest.mark.skipif(
    BASH is None or GIT is None,
    reason="bash and git are required to run a workflow step body",
)


def _steps():
    with open(WORKFLOW, encoding="utf-8") as fh:
        doc = yaml.safe_load(fh)
    (job,) = doc["jobs"].values()
    return job["steps"]


def _step(name):
    for step in _steps():
        if step.get("name") == name:
            return step
    raise AssertionError(f"no step named {name!r} in {WORKFLOW}")


def _git(cwd, *args):
    return subprocess.run(
        [GIT, "-c", "user.name=t", "-c", "user.email=t@t", *args],
        cwd=str(cwd), capture_output=True, text=True, check=True,
    )


PREV_INDEX = "home PREVIOUS CYCLE\n"
PREV_ROSE = "rose PREVIOUS CYCLE\n"
FIRST_INDEX = "home THIS CYCLE (first build)\n"
FIRST_ROSE = "rose THIS CYCLE (first build)\n"
FIRST_ADDED = "tulip THIS CYCLE (a page the first build added)\n"
BOT_HTML = "hand-maintained bot.html, never generated by build.py\n"


def _repo(tmp_path):
    """A repo mid-cycle: HEAD holds the PREVIOUS cycle's committed site/, and
    the worktree holds the FIRST build that 'Build site' just produced.

    That gap is the whole point. If HEAD and the worktree were identical, a
    restore-from-HEAD would be indistinguishable from doing nothing and F5
    could not be observed.
    """
    repo = tmp_path / "repo"
    (repo / "site" / "plants").mkdir(parents=True)
    (repo / "site" / "index.html").write_text(PREV_INDEX, encoding="utf-8")
    (repo / "site" / "plants" / "rose.html").write_text(PREV_ROSE, encoding="utf-8")
    (repo / "site" / "bot.html").write_text(BOT_HTML, encoding="utf-8")
    _git(repo, "init", "-q", "-b", "main")
    _git(repo, "add", "-A")
    _git(repo, "commit", "-qm", "previous cycle")
    # "Build site" runs: new prices produce new HTML, including a NEW page.
    (repo / "site" / "index.html").write_text(FIRST_INDEX, encoding="utf-8")
    (repo / "site" / "plants" / "rose.html").write_text(FIRST_ROSE, encoding="utf-8")
    (repo / "site" / "plants" / "tulip.html").write_text(FIRST_ADDED, encoding="utf-8")
    return repo


def _bindir(tmp_path):
    d = tmp_path / "bin"
    d.mkdir(exist_ok=True)
    return d


def _fake_python(tmp_path, body):
    script = _bindir(tmp_path) / "python"
    script.write_text("#!/bin/sh\n" + textwrap.dedent(body), encoding="utf-8")
    script.chmod(script.stat().st_mode | stat.S_IEXEC)
    return str(_bindir(tmp_path))


def _breaking_git(tmp_path, failing_subcommand):
    """Real git for everything except one subcommand, matched on "$1 $2"."""
    script = _bindir(tmp_path) / "git"
    script.write_text(
        "#!/bin/sh\n"
        f'if [ "$1 $2" = "{failing_subcommand}" ]; then\n'
        '  echo "git: simulated failure" >&2\n'
        "  exit 3\n"
        "fi\n"
        f'exec "{GIT.replace(chr(92), "/")}" "$@"\n',
        encoding="utf-8",
    )
    script.chmod(script.stat().st_mode | stat.S_IEXEC)


def _guard(repo, tmp_path, rebuild):
    """Run the guard body the way Actions runs it. -> (rc, GITHUB_ENV, proc)"""
    script = tmp_path / "step.sh"
    script.write_text(_step(GUARD_STEP)["run"], encoding="utf-8")
    env_file = tmp_path / "github_env"
    env_file.write_text("", encoding="utf-8")
    env = dict(os.environ)
    env["PATH"] = _fake_python(tmp_path, rebuild) + os.pathsep + env["PATH"]
    env["GITHUB_ENV"] = str(env_file)
    env["GIT_AUTHOR_NAME"] = env["GIT_COMMITTER_NAME"] = "t"
    env["GIT_AUTHOR_EMAIL"] = env["GIT_COMMITTER_EMAIL"] = "t@t"
    proc = subprocess.run(
        [BASH, "--noprofile", "--norc", "-e", "-o", "pipefail", str(script)],
        cwd=str(repo), env=env, capture_output=True, text=True,
    )
    return proc.returncode, env_file.read_text(encoding="utf-8"), proc


CRASHING_REBUILD = """\
    printf 'CORRUPT half-writt' > site/index.html
    printf 'CLOBBERED\\n' > site/bot.html
    exit 1
"""
CLEAN_REBUILD = "exit 0\n"

# A crashed rebuild that also leaves an UNTRACKED file behind. `git checkout`
# cannot remove an untracked path -- only `git clean` can -- so this is the
# only shape in which the clean's exit code is observable from the outside.
CRASHING_REBUILD_WITH_JUNK = """\
    printf 'CORRUPT half-writt' > site/index.html
    printf 'JUNK from a crashed rebuild' > site/plants/__junk.html
    exit 1
"""


# --------------------------------------------------------------------------
# F5 — the restore must not run when its precondition did not hold
# --------------------------------------------------------------------------

@needs_bash
def test_a_failed_git_add_does_not_revert_site_to_the_previous_cycle(tmp_path):
    """The headline. `git add` fails, so the index holds HEAD, not the first
    build. An unconditional `git checkout -- site/` therefore publishes LAST
    cycle's HTML next to THIS cycle's prices."""
    repo = _repo(tmp_path)
    _breaking_git(tmp_path, "add -A")
    code, github_env, proc = _guard(repo, tmp_path, CLEAN_REBUILD)
    assert code == 0, f"the guard gated the publish: {proc.stderr}"
    assert "simulated failure" in proc.stderr, "the git shim did not fire"
    assert "REBUILD_CHECK_FAILED=1" in github_env
    assert (repo / "site" / "index.html").read_text(encoding="utf-8") == FIRST_INDEX, (
        "site/index.html was reverted to the PREVIOUS cycle's build while this "
        "cycle's data/ still commits — the remote gets stale HTML beside fresh "
        "prices")
    assert (repo / "site" / "plants" / "rose.html").read_text(encoding="utf-8") == FIRST_ROSE


@needs_bash
def test_a_failed_git_add_does_not_delete_a_page_the_first_build_added(tmp_path):
    """The second half of F5, and the sharper one. A failed `git add` leaves a
    newly built page UNTRACKED, so `git clean -fdq site/` deletes it outright
    — the page 404s on the live site until the next cycle."""
    repo = _repo(tmp_path)
    _breaking_git(tmp_path, "add -A")
    code, _github_env, proc = _guard(repo, tmp_path, CLEAN_REBUILD)
    assert code == 0
    added = repo / "site" / "plants" / "tulip.html"
    assert added.exists(), (
        "git clean deleted a page the first build added, because the failed "
        "git add left it untracked")
    assert added.read_text(encoding="utf-8") == FIRST_ADDED


@needs_bash
def test_the_annotation_does_not_claim_a_restore_that_did_not_happen(tmp_path):
    """The annotation is the only thing a human reads. When `git add` failed,
    it must say the restore could not be done, not assert it was."""
    repo = _repo(tmp_path)
    _breaking_git(tmp_path, "add -A")
    _code, _env, proc = _guard(repo, tmp_path, CLEAN_REBUILD)
    out = proc.stdout
    assert "::error::" in out
    assert "could NOT be restored" in out, (
        f"annotation does not disclose that no restore happened: {out!r}")
    assert "The first build was restored and still publishes" not in out, (
        "the annotation asserts a restore that did not happen")


# --------------------------------------------------------------------------
# F6 — a failed `git checkout` must be reported, not asserted away
# --------------------------------------------------------------------------

@needs_bash
def test_a_failed_git_checkout_is_reported_in_the_annotation(tmp_path):
    """`git checkout`'s rc was discarded, so a restore that did not happen was
    announced as one that did — over half-written HTML and a clobbered
    hand-maintained file."""
    repo = _repo(tmp_path)
    _breaking_git(tmp_path, "checkout --")
    code, github_env, proc = _guard(repo, tmp_path, CRASHING_REBUILD)
    assert code == 0
    assert "simulated failure" in proc.stderr, "the git shim did not fire"
    assert "REBUILD_CHECK_FAILED=1" in github_env
    out = proc.stdout
    assert "git checkout FAILED" in out, (
        f"a failed restore was not disclosed: {out!r}")
    assert "rc=3" in out, f"the checkout's exit code was not reported: {out!r}"
    assert "was restored and still publishes" not in out


@needs_bash
def test_a_failed_git_checkout_says_the_worktree_may_be_half_written(tmp_path):
    """Naming the consequence is the point: whatever is in the worktree is
    what the commit step publishes, and it is the crashed rebuild's output."""
    repo = _repo(tmp_path)
    _breaking_git(tmp_path, "checkout --")
    _code, _env, proc = _guard(repo, tmp_path, CRASHING_REBUILD)
    assert "half-written" in proc.stdout
    # The lie was measurable, not theoretical: this is the state that shipped.
    assert (repo / "site" / "index.html").read_text(encoding="utf-8") == "CORRUPT half-writt"


# --------------------------------------------------------------------------
# F7 -- `git clean`'s exit code must be captured too, not just `git checkout`'s
# --------------------------------------------------------------------------

@needs_bash
def test_a_failed_git_clean_is_reported_and_not_announced_as_a_full_restore(tmp_path):
    """The same unchecked-exit-code class as F6, one line below it.

    `git checkout -- site/` restores TRACKED files. It cannot remove a file the
    crashed rebuild CREATED -- that is `git clean`'s entire job here. So when
    the clean fails and the checkout succeeds, the restore is partial: the
    tracked pages are back, and the crashed rebuild's junk is still sitting in
    site/, where the commit step below will `git add -A site/` it and push it
    to the live site.

    The annotation asserted the opposite -- "The first build WAS restored from
    the index and still publishes" -- because `git clean`'s rc was discarded.
    """
    repo = _repo(tmp_path)
    _breaking_git(tmp_path, "clean -fdq")
    code, github_env, proc = _guard(repo, tmp_path, CRASHING_REBUILD_WITH_JUNK)
    assert code == 0, f"the guard gated the publish: {proc.stderr}"
    assert "simulated failure" in proc.stderr, "the git shim did not fire"
    assert "REBUILD_CHECK_FAILED=1" in github_env

    # The measurable consequence: the junk really is still there, so anything
    # claiming a completed restore is claiming something false.
    junk = repo / "site" / "plants" / "__junk.html"
    assert junk.exists(), (
        "the fixture no longer reproduces the state under test -- `git clean` "
        "was expected to fail and leave the crashed rebuild's file behind")

    out = proc.stdout
    assert "::error::" in out
    assert "git clean FAILED" in out, (
        f"a failed clean was not disclosed: {out!r}")
    assert "rc=3" in out, f"the clean's exit code was not reported: {out!r}"
    assert "WAS restored from the index and still publishes" not in out, (
        "the annotation asserts a completed restore while a crashed rebuild's "
        "untracked file is still in site/ and will be published")


@needs_bash
def test_a_failed_git_clean_still_reports_that_tracked_files_came_back(tmp_path):
    """Honest means accurate in both directions. The checkout DID work, so the
    annotation must not read as though nothing was recovered -- a reader who
    concludes the tracked pages are corrupt will go looking in the wrong
    place, which is the same failure F6 was about."""
    repo = _repo(tmp_path)
    _breaking_git(tmp_path, "clean -fdq")
    _code, _env, proc = _guard(repo, tmp_path, CRASHING_REBUILD_WITH_JUNK)
    assert (repo / "site" / "index.html").read_text(encoding="utf-8") == FIRST_INDEX, (
        "the tracked restore did not happen; this test is no longer about a "
        "PARTIAL restore")
    assert "tracked files were restored" in proc.stdout, (
        f"the annotation does not say the checkout succeeded: {proc.stdout!r}")


# --------------------------------------------------------------------------
# F8 -- a failed `git add` PLUS a crashed rebuild is not "left as-is"
# --------------------------------------------------------------------------

@needs_bash
def test_a_failed_add_with_a_crashed_rebuild_says_the_worktree_may_be_half_written(tmp_path):
    """The `add_rc` gate's justification is "doing nothing is strictly better:
    the first build is still in the worktree". That sentence is true only
    while the rebuild did NOT run far enough to overwrite it.

    When `git add` failed AND the rebuild then crashed mid-write, the first
    build is NOT in the worktree any more -- the crashed rebuild's partial
    output is. Not restoring is still the right call (the index holds HEAD, so
    a restore would publish the previous cycle), but the annotation must stop
    claiming the worktree is intact and say what is actually there, because
    that is what the commit step publishes.
    """
    repo = _repo(tmp_path)
    _breaking_git(tmp_path, "add -A")
    code, github_env, proc = _guard(repo, tmp_path, CRASHING_REBUILD)
    assert code == 0, f"the guard gated the publish: {proc.stderr}"
    assert "simulated failure" in proc.stderr, "the git shim did not fire"
    assert "REBUILD_CHECK_FAILED=1" in github_env

    # The measurable state the annotation has to describe.
    assert (repo / "site" / "index.html").read_text(encoding="utf-8") == "CORRUPT half-writt", (
        "the fixture no longer reproduces the state under test")

    out = proc.stdout
    assert "half-written" in out, (
        f"the annotation does not disclose that the worktree may be "
        f"half-written: {out!r}")
    assert "the worktree was left as-is" not in out, (
        "the annotation still describes an untouched worktree, but the "
        "crashed rebuild overwrote the first build")


def test_the_add_gate_comment_no_longer_claims_the_first_build_survives():
    """The comment is the reason the gate is written the way it is, so a stale
    one is how the next reader reintroduces the bug. It must not state the
    survival of the first build as unconditional fact."""
    run = _step(GUARD_STEP)["run"]
    assert "the first build is still in the worktree" not in run, (
        "the `add_rc` gate's comment still asserts the first build survives a "
        "crashed rebuild; it does not")


# --------------------------------------------------------------------------
# the success path must keep working, and must still say so
# --------------------------------------------------------------------------

@needs_bash
def test_a_crashed_rebuild_is_still_fully_recovered_when_checkout_works(tmp_path):
    """The reason the restore exists at all. Neither fix may weaken it."""
    repo = _repo(tmp_path)
    code, github_env, proc = _guard(repo, tmp_path, CRASHING_REBUILD)
    assert code == 0
    assert "REBUILD_CHECK_FAILED=1" in github_env
    assert (repo / "site" / "index.html").read_text(encoding="utf-8") == FIRST_INDEX, (
        "the half-written rebuild was left in place and would have published")
    assert (repo / "site" / "bot.html").read_text(encoding="utf-8") == BOT_HTML, (
        "a hand-maintained file clobbered by the crashed rebuild was not restored")
    assert "WAS restored from the index" in proc.stdout, (
        f"a successful restore is no longer reported as one: {proc.stdout!r}")


@needs_bash
def test_the_guard_still_reports_a_no_op_when_the_rebuild_reproduces(tmp_path):
    """The state every healthy cycle is in. Neither fix may make it noisy."""
    repo = _repo(tmp_path)
    code, github_env, proc = _guard(repo, tmp_path, CLEAN_REBUILD)
    assert code == 0
    assert "no-op" in proc.stdout
    assert "REBUILD_CHECK_FAILED" not in github_env
    assert "REBUILD_DIVERGED" not in github_env
    assert "::error::" not in proc.stdout


# --------------------------------------------------------------------------
# structure — the surrounding guarantees these fixes sit inside
# --------------------------------------------------------------------------

def test_the_guard_is_still_continue_on_error_and_the_commit_is_not():
    """Neither fix may turn the guard back into a publish gate, and neither
    may be 'fixed' by making the commit unconditional."""
    assert _step(GUARD_STEP).get("continue-on-error") is True
    assert "continue-on-error" not in _step(COMMIT_STEP), (
        "continue-on-error on the commit step would hide a failed publish")
    assert "always()" not in str(_step(COMMIT_STEP).get("if", ""))
    names = [s.get("name") for s in _steps()]
    assert names.index(GUARD_STEP) < names.index(COMMIT_STEP)


def test_the_restore_is_lexically_gated_on_the_add_succeeding():
    """A tripwire for the premise itself. If `git checkout -- site/` ever
    escapes the `add_rc` guard again, the behavioural tests above are the
    proof of what breaks — this one just fails faster and points at why."""
    # Comments only, stripped out — the body's prose quotes both of these
    # strings when explaining the defect, and matching prose would make this
    # test pass for the wrong reason.
    code = [ln.strip() for ln in _step(GUARD_STEP)["run"].splitlines()
            if ln.strip() and not ln.strip().startswith("#")]
    gates = [i for i, ln in enumerate(code) if ln == 'if [ "$add_rc" -eq 0 ]; then']
    checkouts = [i for i, ln in enumerate(code) if ln == "git checkout -- site/"]
    assert gates, "the restore is no longer gated on the git add it assumes succeeded"
    assert checkouts, "the restore disappeared entirely"
    assert min(gates) < min(checkouts), (
        "`git checkout -- site/` runs before the `add_rc` gate, so it can "
        "revert site/ to the previous cycle when `git add` was what failed")
